[package]
name = "agentgraph"
version = "0.1.1"
edition = "2024"
authors = ["CryptoPatrick <cryptopatrick@gmail.com>"]

###############################################################################
description = "Interface for agent graph persistence."
documentation = "https://docs.rs/agentgraph"
homepage = "https://github.com/cryptopatrick/agentgraph"
repository = "https://github.com/cryptopatrick/agentgraph"
readme = "README.md"
keywords = ["AI", "Agent", "Persistence", "Graph"]
license = "MIT"
autotests = false

###############################################################################
[lib]
name = "agentgraph"
path = "src/lib.rs"

[[test]]
name = "tests"
path = "tests/test.rs"

###############################################################################
[dependencies]
